export const LINES_LOAD = 'LINES_LOAD';
export const LINES_ADDED = 'LINES_ADDED';
export const LINES_QUOTE_COORDS_UPDATE = 'LINES_QUOTE_COORDS_UPDATE';
export const LINE_DELETE = 'LINE_DELETE';
export const LINES_DELETE = 'LINES_DELETE';
export const LINES_LOAD_TO_PASTE = 'LINES_LOAD_TO_PASTE';
