export const NOT_EXISTS = 'NOT_EXISTS';

export const ORIG_ACTIVE = 'ORIG_ACTIVE';
export const ORIG_LOADING = 'ORIG_LOADING';
export const ORIG_RESIZE = 'ORIG_RESIZE';
export const ORIG_READY_TO_RECEIVE_PARAMS = 'ORIG_READY_TO_RECEIVE_PARAMS';
export const ORIG_READY = 'ORIG_READY';

export const COMP_ACTIVE = 'COMP_ACTIVE';
export const COMP_LOADING = 'COMP_LOADING';
export const COMP_RESIZE = 'COMP_RESIZE';
export const COMP_READY_TO_RECEIVE_PARAMS = 'COMP_READY_TO_RECEIVE_PARAMS';
export const COMP_READY = 'COMP_READY';
