export const PANEL_TOGGLE = 'PANEL_TOGGLE';
export const PANEL_TOGGLE_MINIMIZE = 'PANEL_TOGGLE_MINIMIZE';
export const PANEL_CHANGE_GEOMETRY = 'PANEL_CHANGE_GEOMETRY';
export const PANEL_CHANGE_MODE = 'PANEL_CHANGE_MODE';
export const PANEL_CHANGE_WIDGET_PARAMS = 'PANEL_CHANGE_WIDGET_PARAMS';
export const PANELS_WIDGETS_QUOTES_RESET = 'PANELS_WIDGETS_QUOTES_RESET';

export const PANELS_SET = 'PANELS_SET';