export const PRESENCE_STATUS_SET = 'PRESENCE_STATUS_SET';
export const PRESENCE_WELCOME = 'PRESENCE_WELCOME';
export const PRESENCE_MEMBERS_SET = 'PRESENCE_MEMBERS_SET';
export const PRESENCE_ERROR_SET = 'PRESENCE_ERROR_SET';
export const PRESENCE_RESET = 'PRESENCE_RESET';
export const PRESENCE_CURSOR_SET = 'PRESENCE_CURSOR_SET';
export const PRESENCE_CURSOR_SHARING_SET = 'PRESENCE_CURSOR_SHARING_SET';
export const PRESENCE_TOUR_ENDED_SET = 'PRESENCE_TOUR_ENDED_SET';
