export const PRESENCE_STATUS_SET = 'PRESENCE_STATUS_SET';
export const PRESENCE_WELCOME = 'PRESENCE_WELCOME';
export const PRESENCE_MEMBERS_SET = 'PRESENCE_MEMBERS_SET';
export const PRESENCE_ERROR_SET = 'PRESENCE_ERROR_SET';
export const PRESENCE_RESET = 'PRESENCE_RESET';
