export const NOTIFICATION_ADD = 'NOTIFICATION_ADD';
export const NOTIFICATION_UPDATE = 'NOTIFICATION_UPDATE';
export const NOTIFICATION_DELETE = 'NOTIFICATION_DELETE';
export const VIEWPORT_SET = 'VIEWPORT_SET';
