export const GAME_LOAD = 'GAME_LOAD';
export const GAME_FIELD_MOVE = 'GAME_FIELD_MOVE';
export const GAME_EDIT_MODE_SWITCH = 'GAME_EDIT_MODE_SWITCH';
export const GAME_CREATE_CANCEL_CALLBACK = 'GAME_CREATE_CANCEL_CALLBACK';
export const GAME_SCREEN_RECT_SET = 'GAME_SCREEN_RECT_SET';

export const GAME_STAGE_SET = 'GAME_STAGE_SET';
export const GAME_VIEWPORT_SET = 'GAME_VIEWPORT_SET';