export const MODAL_CREATE_GAME = 'MODAL_CREATE_GAME';
export const MODAL_ENTER_GAME = 'MODAL_ENTER_GAME';
export const MODAL_DONATE = 'MODAL_DONATE';

export const MODAL_CONFIRM = 'MODAL_CONFIRM';
export const MODAL_UPLOAD = 'MODAL_UPLOAD';
export const MODAL_ACCESS_GAMES = 'MODAL_ACCESS_GAMES';