export const TURNS_UPDATE_GEOMETRY = 'TURNS_UPDATE_GEOMETRY';
export const TURNS_FIELD_WAS_MOVED = 'TURNS_FIELD_WAS_MOVED';
export const TURNS_SCROLL = 'TURNS_SCROLL';
export const TURNS_SYNC_DONE = 'TURNS_SYNC_DONE';
export const TURNS_LOAD_TO_PASTE = 'TURNS_LOAD_TO_PASTE';
export const TURN_WAS_CHANGED = 'TURN_WAS_CHANGED';

export const TURN_CREATE = 'TURN_CREATE';
export const TURN_RESAVE = 'TURN_RESAVE';
export const TURN_DELETE = 'TURN_DELETE';

export const TURN_UPDATE_WIDGET = 'TURN_UPDATE_WIDGET';

export const TURN_NEXT_PASTE_POSITION = 'TURN_NEXT_PASTE_POSITION';

export const TURN_SET_STAGE = 'TURN_SET_STAGE';
export const TURN_PARAGRAPH_SET_STAGE = 'TURN_PARAGRAPH_SET_STAGE';

export const TURNS_SET_LOADING = 'TURNS_SET_LOADING';
export const TURNS_LOAD_GEOMETRY = 'TURNS_LOAD_GEOMETRY';
export const TURNS_LOAD_DATA = 'TURNS_LOAD_DATA';